project:
  type: website
  output-dir: "docs"

website:
  title: "Daniel Cardoso Portela CÃ¢mara"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-cÃ¢mara-5270732b3/
      - icon: github
        href: https://github.com/dcpcamara
      - text: "ðŸ‡§ðŸ‡· PT"
        href: index.html
      - text: "ðŸ‡¬ðŸ‡§ EN"
        href: index-en.html
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

